server:
  port: 8761  # ???? ??? ?? ??? ???
spring:
  application:
    name: discovery-server
eureka:
  client:
    register-with-eureka: false # ?? ??? ???? ??? ???? (???????? true? ?? ?)
    fetch-registry: false # ?? ??? ?? ???? endpoints? ?? ??? ?????? ?? Eureka ??? ??? ???? ??? ?? ( = ???? ???? ????? ??? ???? ?? ?? )
management:
  endpoints:
    web:
      exposure:
        include: '*'
    metrics:
      tags:
        application: ${spring.application.name}
    health:
      diskspace:
        enabled: false