
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Taehk/config_repository.git
#          username: awPskrUY/h10GxF9+0QBkQ==
#          password: RGGBHcfD9eq2q5CPbEPtSL0CJXQ6LpY1
          #?????? ???
server:
  port: 8888
# ???:test
# ????:YBlh7oOgE+ZGdiY2QfpKA5H7hp9VLwlCL+sS7GlC15I=
      # awPskrUY/h10GxF9+0QBkQ==
# ??:RGGBHcfD9eq2q5CPbEPtSL0CJXQ6LpY1